name: Testes e Cobertura

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt
      
      - name: Executar testes com cobertura
        run: |
          pytest --cov=src --cov-report=xml --cov-report=term-missing --cov-fail-under=70 tests/
      
      - name: Upload relatório de cobertura
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml